services:
  api:
    image: doc-cls-gpu:0.1.0
    container_name: news_classification_api
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/model_onnx
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - CUDA_VISIBLE_DEVICES=0  # Specify which GPU to use
    volumes:
      - /home/devmiftahul/nlp/bert_dev/indobenchmark/indobert-large-p2_20250115_091442:/app/model_onnx:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
